# Generated by Django 3.1.7 on 2021-09-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
