# Generated by Django 3.1.7 on 2022-03-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_prefixes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prefixes",
            name="id",
        ),
        migrations.AlterField(
            model_name="prefixes",
            name="prefix",
            field=models.CharField(
                max_length=5, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
